import { IEvent, ISubEvent, ITask, IVendor, ILogistics, IRiskAlert, IChatMessage, IUser } from '../types';

export const INITIAL_USER: IUser = {
  id: 'usr_demo_01',
  name: 'Ananya Sharma',
  email: 'planner@thexperience.ai',
  role: 'Lead Event Director',
};

export const WEDDING_EVENT_ID = 'evt_wedding_001';
export const CORPORATE_EVENT_ID = 'evt_corporate_002';

export const INITIAL_EVENTS: IEvent[] = [
  {
    id: WEDDING_EVENT_ID,
    title: 'The Royal Rajputana Wedding',
    type: 'wedding',
    description: '3-Day Luxury Heritage Wedding of Aria & Kabir with 400 Royal Guests',
    startDate: '2025-11-14',
    endDate: '2025-11-16',
    location: 'Taj Jai Mahal Palace, Jaipur',
    totalGuests: 400,
    budget: 4500000,
    spent: 3150000,
    readinessScore: 84,
    confirmedVendorsCount: 7,
    totalVendorsCount: 7,
    activeRisksCount: 1,
  },
  {
    id: CORPORATE_EVENT_ID,
    title: 'Apex Global Leadership Retreat',
    type: 'corporate',
    description: '2-Day Annual Corporate Retreat & Strategy Summit for 200 Employees',
    startDate: '2025-10-24',
    endDate: '2025-10-25',
    location: 'JW Marriott Walnut Grove, Mussoorie',
    totalGuests: 200,
    budget: 1800000,
    spent: 1120000,
    readinessScore: 78,
    confirmedVendorsCount: 6,
    totalVendorsCount: 6,
    activeRisksCount: 1,
  },
];

export const INITIAL_SUB_EVENTS: ISubEvent[] = [
  // Wedding Sub-Events
  {
    id: 'sub_wed_1',
    eventId: WEDDING_EVENT_ID,
    title: 'Sangeet & Musical Evening',
    day: 1,
    date: '2025-11-14',
    startTime: '19:00',
    endTime: '23:30',
    venue: 'Royal Orchid Grand Lawn',
    expectedGuests: 350,
    status: 'upcoming',
    notes: 'Stage backdrop LED setup & Punjabi Dhol performance.',
  },
  {
    id: 'sub_wed_2',
    eventId: WEDDING_EVENT_ID,
    title: 'Sunlit Haldi Ceremony',
    day: 2,
    date: '2025-11-15',
    startTime: '10:00',
    endTime: '13:00',
    venue: 'Courtyard Pavilion & Poolside',
    expectedGuests: 200,
    status: 'upcoming',
    notes: 'Yellow marigold floral shower with brass urlis.',
  },
  {
    id: 'sub_wed_3',
    eventId: WEDDING_EVENT_ID,
    title: 'Vedic Wedding Ceremony (Pheras)',
    day: 2,
    date: '2025-11-15',
    startTime: '18:00',
    endTime: '22:00',
    venue: 'Grand Haveli Mandap',
    expectedGuests: 400,
    status: 'upcoming',
    notes: 'Baraat procession starting from North Gate at 17:30.',
  },
  {
    id: 'sub_wed_4',
    eventId: WEDDING_EVENT_ID,
    title: 'Grand Royal Reception & Banquet',
    day: 3,
    date: '2025-11-16',
    startTime: '19:30',
    endTime: '23:30',
    venue: 'Crystal Heritage Ballroom',
    expectedGuests: 400,
    status: 'upcoming',
    notes: 'Formal sit-down dinner with live jazz quartet.',
  },

  // Corporate Sub-Events
  {
    id: 'sub_corp_1',
    eventId: CORPORATE_EVENT_ID,
    title: 'Arrival & Welcome Breakfast',
    day: 1,
    date: '2025-10-24',
    startTime: '08:30',
    endTime: '10:00',
    venue: 'Pine Lawn Terraces',
    expectedGuests: 200,
    status: 'upcoming',
    notes: 'Registration desk & lanyard distribution.',
  },
  {
    id: 'sub_corp_2',
    eventId: CORPORATE_EVENT_ID,
    title: 'Experiential Team Building Challenges',
    day: 1,
    date: '2025-10-24',
    startTime: '10:30',
    endTime: '14:00',
    venue: 'Alpine Adventure Arena',
    expectedGuests: 200,
    status: 'upcoming',
    notes: 'Outdoor team simulations & obstacle course.',
  },
  {
    id: 'sub_corp_3',
    eventId: CORPORATE_EVENT_ID,
    title: 'Gala Dinner & Annual Star Awards',
    day: 1,
    date: '2025-10-24',
    startTime: '19:00',
    endTime: '22:30',
    venue: 'Lakeside Pavilion',
    expectedGuests: 200,
    status: 'upcoming',
    notes: 'Live acoustic band and CEO recognition address.',
  },
  {
    id: 'sub_corp_4',
    eventId: CORPORATE_EVENT_ID,
    title: 'Leadership Keynote & Townhall',
    day: 2,
    date: '2025-10-25',
    startTime: '09:30',
    endTime: '12:30',
    venue: 'Grand Himalayan Auditorium',
    expectedGuests: 200,
    status: 'upcoming',
    notes: '2026 Strategic Vision presentation.',
  },
  {
    id: 'sub_corp_5',
    eventId: CORPORATE_EVENT_ID,
    title: 'Farewell Networking Lunch',
    day: 2,
    date: '2025-10-25',
    startTime: '13:00',
    endTime: '15:00',
    venue: 'Valley View Restaurant',
    expectedGuests: 200,
    status: 'upcoming',
    notes: 'Luggage loading and airport departures.',
  },
];

export const INITIAL_TASKS: ITask[] = [
  // Wedding Tasks
  {
    id: 'tsk_wed_1',
    eventId: WEDDING_EVENT_ID,
    title: 'Confirm Sangeet sound-check & stage lighting',
    category: 'entertainment',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Vikram Mehta',
    dueDate: '2025-11-13',
    estimatedCost: 25000,
  },
  {
    id: 'tsk_wed_2',
    eventId: WEDDING_EVENT_ID,
    title: 'Inspect Mandap floral canopy & brass diyas',
    category: 'decor',
    status: 'todo',
    priority: 'high',
    assignee: 'Ritika Roy',
    dueDate: '2025-11-14',
    estimatedCost: 80000,
  },
  {
    id: 'tsk_wed_3',
    eventId: WEDDING_EVENT_ID,
    title: 'Submit final catering headcount (Due in 7 days)',
    category: 'catering',
    status: 'in_progress',
    priority: 'urgent',
    assignee: 'Karan Singhal',
    dueDate: '2025-11-07',
    estimatedCost: 1400000,
  },
  {
    id: 'tsk_wed_4',
    eventId: WEDDING_EVENT_ID,
    title: 'Assign chauffeurs for 150 out-of-town guests',
    category: 'logistics',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Amitabh Sen',
    dueDate: '2025-11-12',
    estimatedCost: 120000,
  },
  {
    id: 'tsk_wed_5',
    eventId: WEDDING_EVENT_ID,
    title: 'Verify Baraat brass band permit with local authorities',
    category: 'general',
    status: 'done',
    priority: 'medium',
    assignee: 'Rajeev Kapoor',
    dueDate: '2025-11-01',
    estimatedCost: 15000,
  },
  {
    id: 'tsk_wed_6',
    eventId: WEDDING_EVENT_ID,
    title: 'Deliver personalized welcome hampers to royal suites',
    category: 'hospitality',
    status: 'todo',
    priority: 'medium',
    assignee: 'Meera Chawla',
    dueDate: '2025-11-13',
    estimatedCost: 65000,
  },

  // Corporate Tasks
  {
    id: 'tsk_corp_1',
    eventId: CORPORATE_EVENT_ID,
    title: 'Coordinate 40 flying-in executives airport transfers',
    category: 'logistics',
    status: 'in_progress',
    priority: 'urgent',
    assignee: 'Devika Nair',
    dueDate: '2025-10-23',
    estimatedCost: 60000,
  },
  {
    id: 'tsk_corp_2',
    eventId: CORPORATE_EVENT_ID,
    title: 'Audit main auditorium 4K LED wall & mic wireless frequencies',
    category: 'entertainment',
    status: 'todo',
    priority: 'high',
    assignee: 'Siddharth Rao',
    dueDate: '2025-10-23',
    estimatedCost: 40000,
  },
  {
    id: 'tsk_corp_3',
    eventId: CORPORATE_EVENT_ID,
    title: 'Resolve HQ bus fleet capacity shortage (150 vs 200)',
    category: 'logistics',
    status: 'blocked',
    priority: 'urgent',
    assignee: 'Devika Nair',
    dueDate: '2025-10-22',
    estimatedCost: 45000,
  },
  {
    id: 'tsk_corp_4',
    eventId: CORPORATE_EVENT_ID,
    title: 'Finalize Star Performer trophy engraving and certificates',
    category: 'general',
    status: 'done',
    priority: 'medium',
    assignee: 'Pooja Verma',
    dueDate: '2025-10-18',
    estimatedCost: 35000,
  },
];

export const INITIAL_VENDORS: IVendor[] = [
  // Wedding Vendors
  {
    id: 'vnd_wed_1',
    eventId: WEDDING_EVENT_ID,
    name: 'Taj Jai Mahal Palace',
    category: 'venue',
    status: 'confirmed',
    cost: 1200000,
    contactName: 'Digvijay Singh',
    phone: '+91 98290 12345',
    email: 'events.jaimahal@tajhotels.com',
    notes: 'All 4 venues booked across 3 days with heritage lighting.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_2', 'sub_wed_3', 'sub_wed_4'],
  },
  {
    id: 'vnd_wed_2',
    eventId: WEDDING_EVENT_ID,
    name: 'Shahi Dawat Royal Caterers',
    category: 'catering',
    status: 'confirmed',
    cost: 1400000,
    contactName: 'Chef Sanjeev Anand',
    phone: '+91 98110 54321',
    email: 'sanjeev@shahidawat.in',
    notes: 'Live counters for Rajasthani, Awadhi, and Continental cuisines.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_2', 'sub_wed_3', 'sub_wed_4'],
  },
  {
    id: 'vnd_wed_3',
    eventId: WEDDING_EVENT_ID,
    name: 'Marigold & Silk Dream Décor',
    category: 'decor',
    status: 'confirmed',
    cost: 750000,
    contactName: 'Tanvi Mathur',
    phone: '+91 97170 99887',
    email: 'tanvi@marigolddream.com',
    notes: 'Mandap canopy design approved. Sangeet floral staging underway.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_2', 'sub_wed_3', 'sub_wed_4'],
  },
  {
    id: 'vnd_wed_4',
    eventId: WEDDING_EVENT_ID,
    name: 'Drishti Cinematic Studios',
    category: 'photography',
    status: 'confirmed',
    cost: 450000,
    contactName: 'Arjun Khandelwal',
    phone: '+91 98300 44556',
    email: 'arjun@drishtistudios.com',
    notes: '4-camera crew, drone coverage, same-day highlight reel.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_2', 'sub_wed_3', 'sub_wed_4'],
  },
  {
    id: 'vnd_wed_5',
    eventId: WEDDING_EVENT_ID,
    name: 'Beats of Punjab Dhol & Live DJ',
    category: 'entertainment',
    status: 'confirmed',
    cost: 180000,
    contactName: 'Gurpreet Singh',
    phone: '+91 99200 66778',
    email: 'info@punjabbeats.com',
    notes: 'Sound equipment license procured for Sangeet & Baraat.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_3'],
  },
  {
    id: 'vnd_wed_6',
    eventId: WEDDING_EVENT_ID,
    name: 'Royal Rajputana Fleet & Chauffeurs',
    category: 'transportation',
    status: 'confirmed',
    cost: 320000,
    contactName: 'Raghav Shekhawat',
    phone: '+91 98280 88990',
    email: 'fleet@royalrajputana.com',
    notes: 'Luxury Innovas & tempo travelers for guest airport transfers.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_2', 'sub_wed_3', 'sub_wed_4'],
  },
  {
    id: 'vnd_wed_7',
    eventId: WEDDING_EVENT_ID,
    name: 'Noor Luxury Concierge & Hospitality',
    category: 'hospitality',
    status: 'confirmed',
    cost: 200000,
    contactName: 'Zoya Qureshi',
    phone: '+91 98101 22334',
    email: 'zoya@noorhosp.com',
    notes: '20 guest relations executives stationed across guest wings.',
    assignedSubEvents: ['sub_wed_1', 'sub_wed_2', 'sub_wed_3', 'sub_wed_4'],
  },

  // Corporate Vendors
  {
    id: 'vnd_corp_1',
    eventId: CORPORATE_EVENT_ID,
    name: 'JW Marriott Walnut Grove Resort',
    category: 'venue',
    status: 'confirmed',
    cost: 700000,
    contactName: 'Sameer Joshi',
    phone: '+91 98970 11223',
    email: 'events.mussoorie@marriott.com',
    notes: '100 deluxe rooms + Grand Auditorium + Lawn reserved.',
    assignedSubEvents: ['sub_corp_1', 'sub_corp_2', 'sub_corp_3', 'sub_corp_4', 'sub_corp_5'],
  },
  {
    id: 'vnd_corp_2',
    eventId: CORPORATE_EVENT_ID,
    name: 'Himalayan Harvest Gourmet Catering',
    category: 'catering',
    status: 'confirmed',
    cost: 380000,
    contactName: 'Chef Rahul Dogra',
    phone: '+91 98160 33445',
    email: 'rahul@himalayanharvest.in',
    notes: 'Buffet meals, high teas, and awards cocktail dinner.',
    assignedSubEvents: ['sub_corp_1', 'sub_corp_2', 'sub_corp_3', 'sub_corp_5'],
  },
  {
    id: 'vnd_corp_3',
    eventId: CORPORATE_EVENT_ID,
    name: 'Summit Pulse AV & Sound Systems',
    category: 'entertainment',
    status: 'confirmed',
    cost: 150000,
    contactName: 'Nitin Roy',
    phone: '+91 98112 77889',
    email: 'nitin@summitpulse.com',
    notes: 'Auditorium stage lighting, teleprompter, sound mixing.',
    assignedSubEvents: ['sub_corp_3', 'sub_corp_4'],
  },
  {
    id: 'vnd_corp_4',
    eventId: CORPORATE_EVENT_ID,
    name: 'Metro Express Charters',
    category: 'transportation',
    status: 'confirmed',
    cost: 220000,
    contactName: 'Harish Bajaj',
    phone: '+91 98103 44556',
    email: 'harish@metroexpress.com',
    notes: 'Contracted for 3x 50-seater buses = 150 capacity (Needs review for 200 PAX).',
    assignedSubEvents: ['sub_corp_1', 'sub_corp_5'],
  },
  {
    id: 'vnd_corp_5',
    eventId: CORPORATE_EVENT_ID,
    name: 'TeamBound Experiential Outings',
    category: 'hospitality',
    status: 'confirmed',
    cost: 180000,
    contactName: 'Capt. Sunil Nair',
    phone: '+91 98450 66771',
    email: 'sunil@teambound.com',
    notes: 'Safety gear, facilitators, and customized team challenges.',
    assignedSubEvents: ['sub_corp_2'],
  },
  {
    id: 'vnd_corp_6',
    eventId: CORPORATE_EVENT_ID,
    name: 'Apex Visuals Media Crew',
    category: 'photography',
    status: 'confirmed',
    cost: 120000,
    contactName: 'Shreya Kapoor',
    phone: '+91 98204 99001',
    email: 'shreya@apexvisuals.com',
    notes: 'Keynote streaming, photo shoots, awards coverage.',
    assignedSubEvents: ['sub_corp_3', 'sub_corp_4'],
  },
];

export const INITIAL_LOGISTICS: ILogistics[] = [
  {
    id: 'log_wed_1',
    eventId: WEDDING_EVENT_ID,
    outOfTownGuests: 150,
    hotelRoomsRequired: 75,
    hotelRoomsBooked: 75,
    airportShuttlesRequired: 20,
    airportShuttlesAssigned: 16,
    fleetCapacityRequired: 200,
    fleetCapacityAllocated: 160,
    notes: '150 out-of-town guests arriving across 2 terminals. Rooms booked at Taj Palace and adjoining wing.',
  },
  {
    id: 'log_corp_1',
    eventId: CORPORATE_EVENT_ID,
    outOfTownGuests: 40,
    hotelRoomsRequired: 100,
    hotelRoomsBooked: 100,
    airportShuttlesRequired: 8,
    airportShuttlesAssigned: 8,
    fleetCapacityRequired: 200,
    fleetCapacityAllocated: 150,
    notes: '40 employees flying in from South & West regional offices. 160 departing from NCR HQ.',
  },
];

export const INITIAL_RISKS: IRiskAlert[] = [
  // Wedding Initial Risk
  {
    id: 'rsk_wed_1',
    eventId: WEDDING_EVENT_ID,
    title: 'Catering Final Headcount Due in 7 Days',
    severity: 'warning',
    type: 'deadline',
    message: 'Shahi Dawat Caterers requires locked guest count (estimated 400) by Nov 7 to procure organic spices & premium meats without late surcharge.',
    impact: 'Potential 15% procurement penalty and buffet shortages if count is not submitted on time.',
    resolved: false,
    recommendedActions: [
      {
        id: 'act_wed_rsk_1_1',
        label: 'Send RSVP Nudge to 38 Pending Guests',
        actionType: 'SEND_RSVP_NUDGE',
        payload: { eventId: WEDDING_EVENT_ID, count: 38 },
      },
      {
        id: 'act_wed_rsk_1_2',
        label: 'Lock Headcount at 400 (+5% Buffer)',
        actionType: 'LOCK_CATERING_HEADCOUNT',
        payload: { eventId: WEDDING_EVENT_ID, finalCount: 420 },
      },
    ],
    createdAt: new Date().toISOString(),
  },

  // Corporate Initial Risk
  {
    id: 'rsk_corp_1',
    eventId: CORPORATE_EVENT_ID,
    title: 'Transport Capacity Deficit (50 Stranded Attendees)',
    severity: 'critical',
    type: 'capacity_deficit',
    message: 'Contracted Metro Express fleet capacity is 150 seats, but 200 attendees are departing HQ on Day 1 morning.',
    impact: '50 employees will lack transit to the retreat resort, jeopardizing Day 1 Team Building at 10:30 AM.',
    resolved: false,
    recommendedActions: [
      {
        id: 'act_corp_rsk_1_1',
        label: 'Book 50-Seater Tempo Fleet (+₹45,000)',
        actionType: 'BOOK_ADDITIONAL_TRANSPORT',
        payload: { eventId: CORPORATE_EVENT_ID, additionalCapacity: 50, cost: 45000 },
      },
      {
        id: 'act_corp_rsk_1_2',
        label: 'Split into 2 Departure Batches (07:00 AM & 08:30 AM)',
        actionType: 'SPLIT_DEPARTURE_BATCHES',
        payload: { eventId: CORPORATE_EVENT_ID, batches: 2 },
      },
    ],
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_CHAT_MESSAGES: Record<string, IChatMessage[]> = {
  [WEDDING_EVENT_ID]: [
    {
      id: 'msg_wed_init_1',
      eventId: WEDDING_EVENT_ID,
      sender: 'ai',
      text: 'Namaste! I am your PlanCraft AI Co-Pilot for The Royal Rajputana Wedding. All 4 sub-events are synchronized. Current health readiness is 84%. You can test any scenario below or type an update.',
      timestamp: '10:00 AM',
      extractedEntities: {
        dates: ['Nov 14-16, 2025'],
        headcounts: [400],
        vendors: ['Taj Jai Mahal', 'Shahi Dawat', 'Drishti Studios'],
      },
      suggestedActions: [
        {
          id: 'sugg_1',
          label: 'Review Catering 7-Day Deadline',
          actionType: 'NAVIGATE_TAB',
          payload: { tab: 'risks' },
        },
        {
          id: 'sugg_2',
          label: 'Inspect Sangeet Decor Status',
          actionType: 'NAVIGATE_TAB',
          payload: { tab: 'timeline' },
        },
      ],
    },
  ],
  [CORPORATE_EVENT_ID]: [
    {
      id: 'msg_corp_init_1',
      eventId: CORPORATE_EVENT_ID,
      sender: 'ai',
      text: 'Welcome! I am your PlanCraft AI Co-Pilot for the Apex Global Leadership Retreat. I have flagged 1 critical risk: Fleet capacity is currently 150 for 200 attendees. What would you like to resolve first?',
      timestamp: '09:00 AM',
      extractedEntities: {
        dates: ['Oct 24-25, 2025'],
        headcounts: [200],
        vendors: ['JW Marriott Walnut Grove', 'Metro Express Charters'],
      },
      suggestedActions: [
        {
          id: 'sugg_corp_1',
          label: 'Resolve Transport Deficit',
          actionType: 'RESOLVE_RISK',
          payload: { riskId: 'rsk_corp_1' },
        },
      ],
    },
  ],
};
